[package]
name = "lechenaultia"
version = "0.1.0"
authors = ["tokizuoh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
rand = "0.7.3"